ip_v6 = false
server_port = 10090
#proxy_addresses = ["127.0.0.1:80"]
proxy_addresses = ["45.32.10.177:8080"]
authentication = "user1"
worker_thread_number = 64
log_dir = "log"
log_name_prefix = "ppaass-agent-v3"
max_log_level = "debug"
rsa_dir = "resources/rsa"