ip_v6 = false
server_port = 10090
proxy_addresses = ["127.0.0.1:8080"]
#proxy_addresses = ["45.32.10.177:8080"]
#proxy_addresses = ["45.77.75.244:8080"]
authentication = "user1"
worker_thread_number = 64
log_dir = "log"
log_name_prefix = "ppaass-agent-v3"
max_log_level = "error"
rsa_dir = "resources/rsa"
agent_to_proxy_data_relay_buffer_size = 131072
proxy_to_agent_data_relay_buffer_size = 131072
proxy_framed_buffer_size = 262144
proxy_connect_timeout = 10
# The connection pool configuration
[connection_pool]
max_pool_size = 32
fill_interval = 5
connection_retake_interval = 1
check_interval = 10
connection_max_alive = 300
heartbeat_timeout = 10
