ip_v6 = false
server_port = 80
worker_thread_number = 64
log_dir = "log"
log_name_prefix = "ppaass-server-v3"
max_log_level = "trace"
agent_rsa_dir = "resources/agent_rsa"
forward_rsa_dir = "resources/forward_rsa"
forward_proxies = [
    { proxy_address = "127.0.0.1:10091", proxy_auth = "proxy_forward_user1" },
    { proxy_address = "127.0.0.1:10092", proxy_auth = "proxy_forward_user1" },
    { proxy_address = "127.0.0.1:10093", proxy_auth = "proxy_forward_user1" }
]