ip_v6 = false
server_port = 10092
worker_thread_number = 64
log_dir = "log"
log_name_prefix = "ppaass-proxy-v3"
max_log_level = "error"
rsa_dir = "resources/agent_rsa"
proxy_to_destination_data_relay_buffer_size = 32768
destination_to_proxy_data_relay_buffer_size = 32768
destination_connect_timeout = 10
agent_frame_buffer_size = 262144